### ISSUE TITLE
Wts S_DELETE_FRIEND for NA

### ISSUE THREAD

**Issue by TerableCoder** [Leyki/tera-colorful-whispers#4]
S_DELETE_FRIEND = 20195
https://github.com/TerableCoder/Tera-NA-Opcodes

**Comment by Leyki** [comment]
Sorry for the big delay. While i left that comment in the code it wasn't in such a way. However i don't want to have users to install op codes or have to hardcode them myself so i'd rather not use what's not mappe, that said, i appreciate the intention.
